name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Terraform environment"
        required: true
        type: choice
        options:
          - poc
        default: poc

      confirm:
        description: "Type yes to apply"
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  terraform-apply:
    if: ${{ inputs.confirm == 'yes' }}
    runs-on: ubuntu-latest
    environment: poc

    env:
      TF_ENV: ${{ inputs.environment || 'poc' }}

      ARM_USE_OIDC: true
      ARM_CLIENT_ID: ${{ vars.AZURE_CONTROL_CLIENT_ID }}
      ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CONTROL_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -backend-config="key=$TF_ENV/terraform.tfstate"

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="environments/$TF_ENV.tfvars" -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan